import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const verdana = localFont({
  src: [
    {
      path: "/../public/fonts/Verdana.ttf",
      weight: "700",
      style: "normal"
    },
    {
      path: "/../public/fonts/VerdanaPro-Regular.ttf",
      weight: "400",
      style: "normal"
    }
  ]
});

export const metadata: Metadata = {
  title: "Houses",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={verdana.className}>{children}</body>
    </html>
  );
}
